cells=c(1,3,5,7,8,9,11,12,14)
rnames=c("row1","row2","row3")
cnames=c("col1","col2","col3")
m2=matrix(cells,nrow=3,ncol=3,byrow=TRUE,dimnames=list(rnames,cnames))
print("3*3 matrix wit labels,filled by rows:")
print(m2)
print("3*3 matrix wit labels,filled by columns:")
m3=matrix(cells,nrow=3,ncol=3,byrow=FALSE,dimnames=list(rnames,cnames))
print(m3)
